feat:creating call to action section
TheGymRwanda/unitA pull request #10
Opened 2023-01-10 14:15 UTC by arjorb

## Describe your changes
we created a call to action section and add a button component to it for scheduling a call
## Issue ticket number and link
id -> 017
link -> [Here](https://www.notion.so/apeunit/call-to-action-section-8e171fa6ea424fb78bf7afb5572622ba)
## Tasks completed
- [x] Creating a call to action section
## Tasks not completed
None
## Screenshots (if needed)
None

2023-01-10 15:53 UTC, jacob-js requested changes
# Good job @arjorb 

Only some few issues to fix. kindly refer to my comments

2023-01-10 15:53 UTC, jacob-js commented on components/sections/homepage/CallToAction/index.jsx
> +        <h1 className='text-custom-3xl'>Ready to talk about your project?</h1>
This heading must have a font weight of 600

2023-01-10 15:53 UTC, jacob-js commented on components/sections/homepage/CallToAction/index.jsx
> +        </p>
This paragraph here doesn't have any margin top, make sure to check the value correctly in Figma

2023-01-10 15:53 UTC, jacob-js commented on components/sections/homepage/CallToAction/index.jsx
> +          <Button>Schedule a call</Button>
Make sure to use the button's `size` prop to make it a bit large than it is. The value `large` it is used to give it a large size

2023-01-11 10:26 UTC, mutesialine submitted a review, later dismissed
It's looks good

2023-01-11 10:37 UTC, jacob-js approved these changes

2023-01-11 10:38 UTC, mutesialine approved these changes

2023-01-11 10:38 UTC, merged