feat: project section and it's responsiveness
TheGymRwanda/unitA pull request #13
Opened 2023-01-10 15:46 UTC by mutesialine

## Describe your changes
created projects folder  and added it's content
## Issue ticket number and link
id->15
link->[here](https://www.notion.so/apeunit/Project-section-9e6de12cf0a540c08316e1b9f9ad1180)
## Tasks completed
- [x ] we create a projects folder and its file
- [x]we added content and its responsive to desktop, tablet and mobile
- [x] we created a data folder for the projects
- [x]  added some configuration in tailwindconfig folder

## Tasks not completed
None
## Screenshots (if needed)
None

2023-01-10 16:55 UTC, hirwaaldo1 requested changes
Well done but you can change the following

2023-01-10 16:55 UTC, hirwaaldo1 commented on pages/index.jsx
> +      </Wrapper>
Don't call the wrapper in this file, call it instead inside the component in which it's being used

2023-01-11 10:06 UTC, hirwaaldo1 approved these changes
Well done

2023-01-11 10:06 UTC, arjorb approved these changes

2023-01-11 10:08 UTC, merged